# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Item.create([
  { :content => "Threaded ends, brazed.", :user_id => 1, :created_at => "2013-02-25 17:34:35", :updated_at => "2013-02-25 17:34:35", :title => "20\" Schedule 40 PVC Pipe" },
  { :content => "We've got a whole box of these things.", :user_id => 1, :created_at => "2013-02-25 17:44:17", :updated_at => "2013-02-25 17:44:17", :title => "4\" 90 Elbow Sch40" },
  { :content => "Apollo 6\" 82-24A-A1", :user_id => 1, :created_at => "2013-02-25 17:45:21", :updated_at => "2013-02-25 17:45:21", :title => "4\" Oxygen Cleaned Med Gas Ball Valve" },
  { :content => "Various Sizes. 2\" to 6\", 304 SS.", :user_id => 1, :created_at => "2013-02-25 17:45:57", :updated_at => "2013-02-25 17:45:57", :title => "Clevis Hangers" },
  { :content => "Food grade, Stainless Steel, In Box", :user_id => 1, :created_at => "2013-02-25 17:47:37", :updated_at => "2013-02-25 17:47:37", :title => "3\" Carbon Steel 45 Elbows" },
  { :content => "A shed full of Copper Tube.", :user_id => 1, :created_at => "2013-02-25 17:48:10", :updated_at => "2013-02-25 17:48:10", :title => "85' Copper Type L Tubing, 3\"" },
  { :content => "Great shape. Just sitting around.", :user_id => 2, :created_at => "2013-02-25 17:49:55", :updated_at => "2013-02-25 17:49:55", :title => "1000' 4\" S40 PVC Pipe" },
  { :content => "", :user_id => 2, :created_at => "2013-02-25 17:50:31", :updated_at => "2013-02-25 17:50:31", :title => "6\" Triple Duty Valve, Bell & Gossett" },
  { :content => "", :user_id => 2, :created_at => "2013-02-25 17:52:05", :updated_at => "2013-02-25 17:52:05", :title => "1 x 1-1/2 Propress Copper Tee" },
  { :content => "", :user_id => 2, :created_at => "2013-02-25 17:52:18", :updated_at => "2013-02-25 17:52:18", :title => "1\" PP 90" }
], :without_protection => true )



User.create([
  { :email => "michaelomchenry@gmail.com", :encrypted_password => "$2a$10$fzWyEX9bbR/WtkGaq.d1FujywnRrNdrnda1C6yVsPYH2QkwpCxnyC", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 3, :current_sign_in_at => "2013-02-25 17:37:41", :last_sign_in_at => "2013-02-25 17:34:52", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-02-25 17:34:20", :updated_at => "2013-02-25 17:37:41", :username => "momchenr" },
  { :email => "bouncearoundtheroom@hotmail.com", :encrypted_password => "$2a$10$0VZPd5lr1D/vlbR6IrKt4ep93CyhEm/dUvY8niJISDJRPw01tZ6O6", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 2, :current_sign_in_at => "2013-02-25 17:49:26", :last_sign_in_at => "2013-02-25 17:48:30", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-02-25 17:48:29", :updated_at => "2013-02-25 17:49:26", :username => "phishhead" }
], :without_protection => true )


